FROM {{ base_image }}
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY ["requirements.txt", "/app/requirements.txt"]
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY ["main.py", "/app/main.py"]
COPY ["node-manifest.json", "/app/node-manifest.json"]
LABEL inlumen.flow_id="{{ flow_id }}"
LABEL inlumen.generator="wikifier"
CMD ["python", "/app/main.py"]
